### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by tayglobal** [tayglobal/ak-check-in#55]
To protect information about members. Let's encrypt to traffic.

**Comment by tayglobal** [comment]
This will need front end change to add an input encryption key and backend change to encrypt the traffic

**Comment by LyuboDias** [comment]
hey @tayglobal  can you create a new task for that and assign it to me, Im gonna need more details on what exactly is needed as not very familiar with the issue :)

**Comment by tayglobal** [comment]
Here it is

https://github.com/tayglobal/ak-check-in/issues/68

**Comment by tayglobal** [comment]
Let's Authenticate rather than encrypt

**Comment by tayglobal** [comment]
Hi @LyuboDias can you make the UI changes here? 
Please continue with the branch ``55-add-authentication``, can't merge to ``main`` yet or the example would break.

I've update the mock server to require authentication.

All the request now needed a bearer token per ``tests/mock_messages/README.md``

To get the initial state. This represent the current state of the screen used when the UI first initialises. 

Make sure to replace ``MY_DUMMY_TOKEN`` with your token encrypted in ``.env``

```
curl -H "Content-Type: application/json" -H "Authorization: Bearer MY_DUMMY_TOKEN" http://127.0.0.1:8765/initial_state 
```

So in the UI, after user entered the token, you can start making requests to the server and include the token in the request header.
