### ISSUE TITLE
Clock's timezone should be based on the gym and not the browser

### ISSUE THREAD

**Issue by tayglobal** [tayglobal/ak-check-in#57]
Would be good to display the gym's timezone instead of, in my case Tokyo Time Zone.
Or at least allow an option to choose how to display it

**Comment by LyuboDias** [comment]
- use GMT if no initial_state.time_zone_name present
- add date to Clock component

**Comment by tayglobal** [comment]
Use ``Intl.DateTimeFormat`` for this
