### ISSUE TITLE
Decrypt message from PubNub

### ISSUE THREAD

**Issue by tayglobal** [tayglobal/ak-check-in#76]
Once server side can encrypt the message https://github.com/tayglobal/ak-check-in/issues/55
and we have a UI component to enter the encryption key: https://github.com/tayglobal/ak-check-in/issues/68

Use something similar to the below to decrypt it.

Example code for decription

```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"></script>

<script>
function decrypt_message(ciphertext, key) {
    const decodedKey = atob(key); // Decode Base64-encoded key
    const cipherBytes = CryptoJS.AES.decrypt(ciphertext.toString(), decodedKey); 
    const decryptedText = cipherBytes.toString(CryptoJS.enc.Utf8);
    return decryptedText;
}

// Assuming you have received the ciphertext and key from Python
const ciphertext = "..."; // (Replace with the ciphertext)
const key = "..."; // (Replace with the base64-encoded key)

const decryptedMessage = decrypt_message(ciphertext, key);
console.log(decryptedMessage);  
</script>   
```

**Comment by LyuboDias** [comment]
@tayglobal sorry but we need to have a call about this to understand whats the work I need to do :)

**Comment by tayglobal** [comment]
Cool let me schedule a call

**Comment by tayglobal** [comment]
In fact don't worry about it. You focus on the UI part. I'll take this one

**Comment by tayglobal** [comment]
Done. Decided to use Authentication rather than encryption
